export const mockJobPosts = [
  {
    id: 1,
    title: "Frontend Developer",
    description: "Looking for React developer with 2+ years experience",
    location: "Bangalore",
    salaryRange: "₹50000-70000",
    experience: "2-4 years",
    employmentType: "Full-time",
    skills: ["React", "JavaScript", "CSS"],
    candidateCount: 3,
    postedDate: "2024-01-10",
  },
  {
    id: 2,
    title: "Backend Developer",
    description: "Experienced Node.js developer needed",
    location: "Mumbai",
    salaryRange: "₹60000-80000",
    experience: "3-5 years",
    employmentType: "Full-time",
    skills: ["Node.js", "MongoDB", "Express"],
    candidateCount: 2,
    postedDate: "2024-01-12",
  },
  {
    id: 3,
    title: "Full Stack Engineer",
    description: "Full stack developer with React and Node.js experience",
    location: "Pune",
    salaryRange: "₹70000-90000",
    experience: "4-6 years",
    employmentType: "Full-time",
    skills: ["React", "Node.js", "PostgreSQL"],
    candidateCount: 2,
    postedDate: "2024-01-15",
  },
  {
    id: 4,
    title: "DevOps Engineer",
    description: "DevOps engineer with AWS and Docker experience",
    location: "Hyderabad",
    salaryRange: "₹80000-100000",
    experience: "5-7 years",
    employmentType: "Full-time",
    skills: ["AWS", "Docker", "Kubernetes"],
    candidateCount: 1,
    postedDate: "2024-01-08",
  },
]

export const mockCandidates = [
  {
    id: 1,
    jobPostId: 1,
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "+1 (555) 123-4567",
    position: "Frontend Developer",
    experience: "5 years",
    status: "Completed",
    appliedDate: "2024-01-15",
    interviewDate: "2024-01-25",
    score: 85,
    fitScore: "85%",
    skills: ["React", "TypeScript", "Node.js", "GraphQL"],
    education: "BS Computer Science - MIT",
    location: "San Francisco, CA",
    resume: "sarah_johnson_resume.pdf",
    coverLetter: "sarah_johnson_cover.pdf",
    portfolio: "https://sarahjohnson.dev",
    notes:
      "Strong technical background with excellent communication skills. Previous experience at top tech companies. Demonstrated deep understanding of React ecosystem and modern frontend development practices. Shows great potential for leadership roles.",
    interviewTranscript:
      "Candidate showed excellent problem-solving skills during the technical interview. Discussed previous projects in detail and demonstrated strong understanding of React patterns and best practices. Communication was clear and professional throughout.",
    interviewRounds: [
      { round: "Phone Screen", status: "Completed", score: 90, date: "2024-01-18" },
      { round: "Technical", status: "Completed", score: 85, date: "2024-01-25" },
    ],
  },
  {
    id: 2,
    jobPostId: 1,
    name: "Amanda White",
    email: "amanda.w@email.com",
    phone: "+1 (555) 123-4568",
    position: "Frontend Developer",
    experience: "2 years",
    status: "Completed",
    appliedDate: "2024-01-12",
    interviewDate: "2024-01-22",
    score: 78,
    fitScore: "78%",
    skills: ["HTML", "CSS", "JavaScript", "Vue.js"],
    education: "Bootcamp Graduate - General Assembly",
    location: "Los Angeles, CA",
    resume: "amanda_white_resume.pdf",
    coverLetter: "amanda_white_cover.pdf",
    notes:
      "Good foundational skills in frontend development. Shows enthusiasm and willingness to learn. Needs more experience with complex applications but has strong potential for growth.",
    interviewTranscript:
      "Candidate demonstrated basic understanding of frontend concepts. Struggled with some advanced questions but showed good problem-solving approach. Needs more hands-on experience with larger projects.",
    interviewRounds: [
      { round: "Phone Screen", status: "Completed", score: 75, date: "2024-01-15" },
      { round: "Technical", status: "Completed", score: 78, date: "2024-01-22" },
    ],
  },
  {
    id: 3,
    jobPostId: 1,
    name: "Jessica Taylor",
    email: "jessica.t@email.com",
    phone: "+1 (555) 234-5678",
    position: "Frontend Developer",
    experience: "3 years",
    status: "Pending",
    appliedDate: "2024-01-22",
    score: 0,
    fitScore: "---",
    skills: ["React", "JavaScript", "CSS", "Redux"],
    education: "BS Computer Science - UCLA",
    location: "Los Angeles, CA",
    resume: "jessica_taylor_resume.pdf",
    coverLetter: "jessica_taylor_cover.pdf",
    notes: "Application under review. Initial screening pending.",
    interviewRounds: [],
  },
  {
    id: 4,
    jobPostId: 2,
    name: "Michael Chen",
    email: "m.chen@email.com",
    phone: "+1 (555) 234-5678",
    position: "Backend Developer",
    experience: "3 years",
    status: "Pending",
    appliedDate: "2024-01-16",
    score: 0,
    fitScore: "---",
    skills: ["Python", "Django", "React", "PostgreSQL"],
    education: "MS Software Engineering - Stanford",
    location: "Seattle, WA",
    resume: "michael_chen_resume.pdf",
    coverLetter: "michael_chen_cover.pdf",
    portfolio: "https://michaelchen.io",
    notes:
      "Solid full-stack experience. Good problem-solving skills demonstrated in coding challenge. Awaiting technical interview.",
    interviewRounds: [{ round: "Phone Screen", status: "Completed", score: 78, date: "2024-01-19" }],
  },
  {
    id: 5,
    jobPostId: 2,
    name: "Alex Thompson",
    email: "alex.t@email.com",
    phone: "+1 (555) 678-9012",
    position: "Backend Developer",
    experience: "2 years",
    status: "Completed",
    appliedDate: "2024-01-17",
    score: 72,
    fitScore: "72%",
    skills: ["Java", "Spring Boot", "MySQL", "Redis"],
    education: "BS Computer Science - Georgia Tech",
    location: "Atlanta, GA",
    resume: "alex_thompson_resume.pdf",
    coverLetter: "alex_thompson_cover.pdf",
    notes: "Junior developer with good potential. Needs more experience but shows promise in backend development.",
    interviewTranscript:
      "Candidate demonstrated solid understanding of backend fundamentals. Good grasp of database concepts and API design. Shows potential for growth with proper mentorship.",
    interviewRounds: [{ round: "Phone Screen", status: "Completed", score: 72, date: "2024-01-20" }],
  },
  {
    id: 6,
    jobPostId: 3,
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "+1 (555) 345-6789",
    position: "Full Stack Engineer",
    experience: "4 years",
    status: "Completed",
    appliedDate: "2024-01-10",
    interviewDate: "2024-01-20",
    score: 92,
    fitScore: "92%",
    skills: ["React", "Node.js", "PostgreSQL", "AWS"],
    education: "BS Computer Science - MIT",
    location: "New York, NY",
    resume: "emily_rodriguez_resume.pdf",
    coverLetter: "emily_rodriguez_cover.pdf",
    portfolio: "https://emilyrodriguez.dev",
    notes:
      "Exceptional full-stack developer with strong technical skills. Excellent problem-solving abilities and communication. Has experience leading small teams and mentoring junior developers.",
    interviewTranscript:
      "Outstanding interview performance. Demonstrated deep understanding of both frontend and backend technologies. Provided excellent solutions to complex problems and showed strong system design skills.",
    interviewRounds: [
      { round: "Phone Screen", status: "Completed", score: 88, date: "2024-01-12" },
      { round: "Technical", status: "Completed", score: 95, date: "2024-01-17" },
      { round: "Final", status: "Completed", score: 93, date: "2024-01-20" },
    ],
  },
  {
    id: 7,
    jobPostId: 3,
    name: "James Wilson",
    email: "james.w@email.com",
    phone: "+1 (555) 890-1234",
    position: "Full Stack Engineer",
    experience: "5 years",
    status: "Completed",
    appliedDate: "2024-01-09",
    interviewDate: "2024-01-19",
    score: 87,
    fitScore: "87%",
    skills: ["React", "Node.js", "MongoDB", "Docker"],
    education: "BS Software Engineering - UT Austin",
    location: "Austin, TX",
    resume: "james_wilson_resume.pdf",
    coverLetter: "james_wilson_cover.pdf",
    portfolio: "https://jameswilson.dev",
    notes:
      "Excellent full-stack development skills. Has experience with microservices architecture and cloud deployment.",
    interviewTranscript:
      "Strong technical interview. Demonstrated expertise in both frontend and backend development. Good understanding of DevOps practices and CI/CD pipelines.",
    interviewRounds: [
      { round: "Phone Screen", status: "Completed", score: 85, date: "2024-01-12" },
      { round: "Technical", status: "Completed", score: 89, date: "2024-01-19" },
    ],
  },
  {
    id: 8,
    jobPostId: 4,
    name: "David Kim",
    email: "david.k@email.com",
    phone: "+1 (555) 456-7890",
    position: "DevOps Engineer",
    experience: "6 years",
    status: "Completed",
    appliedDate: "2024-01-08",
    interviewDate: "2024-01-18",
    score: 88,
    fitScore: "88%",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform"],
    education: "BS Computer Engineering - UC Berkeley",
    location: "Austin, TX",
    resume: "david_kim_resume.pdf",
    coverLetter: "david_kim_cover.pdf",
    notes:
      "Strong DevOps background with extensive cloud infrastructure experience. Has led multiple successful cloud migration projects.",
    interviewTranscript:
      "Excellent technical knowledge of cloud infrastructure and DevOps practices. Demonstrated strong understanding of CI/CD pipelines and infrastructure as code.",
    interviewRounds: [
      { round: "Phone Screen", status: "Completed", score: 85, date: "2024-01-11" },
      { round: "Technical", status: "Completed", score: 90, date: "2024-01-18" },
    ],
  },
]
